name: Deploy Vue App to GitHub Pages

on:
  push:
    branches:
      - main # Set this to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: "ethanfox"
          reponame: "art-institue-chicago"
          token: ${{ secrets.GITHUB_TOKEN }} # Leave this as is, it's automatically provided
